app:
  mode: debug # or release
  max_multipart_memory: 10 # MiB
  trusted_proxies:
    - "127.0.0.1"
    - "::1"
    - "0.0.0.0"
  app_logger_filepath: "./logs/app.log"
  addr: ":8080"

auth:
  auth_expiration: 24

email_broker:
  from_email: "noreply@example.com"
  smtp_host: "smtp.example.com"
  smtp_port: 587
  smtp_password: "your-smtp-password"

product_image:
  max_product_images_amount: 6

payment:
  zp_merchant_id: "YOUR_ZARINPAL_MERCHANT_ID"
  payment_callback_url: "https://example.com/payment/callback"

file_upload:
  allowed_image_mimetype:
    - "image/jpeg"
    - "image/png"
    - "image/webp"
    - "image/gif"
    - "image/avif"
  aws_s3:
    key: "YOUR_AWS_ACCESS_KEY_ID"
    secret: "YOUR_AWS_SECRET_ACCESS_KEY"
    region: "us-east-1"
    endpoint: "https://s3.amazonaws.com"

request_logger_filepath: "./logs/request.log"

origins:
  - "https://example.com"
  - "http://localhost:3000"

database_url: "postgres://username:password@localhost:5432/mydb?sslmode=disable"

cache_url: "redis://localhost:6379/"

pagination: 20

jwt_secret_key: "your-super-secret-jwt-key"
