user nobody nobody;

worker_processes        auto;
worker_cpu_affinity     auto;
worker_shutdown_timeout 60s;

error_log /var/log/nginx/nginx-error.log info;
pid       /run/nginx.pid;

events {
    worker_connections 2048;
}

http {
    add_header_inherit merge;
    server_tokens off;
    include mime.types;

    etag on;

    gzip on;
    gzip_types text/plain
        text/css
        text/xml
        application/json
        application/javascript
        application/xml
        image/svg+xml;
    gzip_vary on;

    client_header_timeout 60s;
    client_body_timeout   60s;
    disable_symlinks      on;
    keepalive_time        2m;

    # error_log_tag request_id $request_id;

    resolver         127.0.0.1 valid=300s;
    resolver_timeout 10s;

    map $http_origin $allow_origin {
        default "";

        "~^https?://localhost(:[0-9]+)?$" $http_origin;
        "~^https?://example\.com$"        $http_origin;
    }
    server {
        listen      8080 default_server;
        server_name proxyserver;

        add_header X-Frame-Options           "DENY" always;
        add_header X-Content-Type-Options    "nosniff" always;
        add_header Referrer-Policy           "strict-origin-when-cross-origin" always;
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

        add_header Access-Control-Allow-Origin      $allow_origin always;
        add_header Access-Control-Allow-Credentials "true" always;
        add_header Vary                             "Accept-Encoding, Origin" always;

        location /api/ {
            # CORS handler
            if ($request_method = OPTIONS) {
                add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
                add_header Access-Control-Allow-Headers "Origin, Content-Type, Accept, Authorization" always;
                add_header Access-Control-Expose-Headers "X-Max-Page" always;
                add_header Access-Control-Max-Age       86400 always;

	            return 204; # no content
            }

            proxy_http_version 1.1;

            proxy_pass       http://backend:8080;
            proxy_set_header Host            $host;
            proxy_set_header X-Forwarded-For $remote_addr;
        }
        # location / {
        #     root      /app/;
        #     try_files $uri $uri/ $uri/index.html $uri.html =404;
        #     index     index.html;
        # }
        # location /videos/ {
        #     aio threads;
        #     output_buffers 1 64k;
        # }
    }

    # error_page 404 /404.html;
}

